language: node_js
node_js:
- '0.12'
deploy:
  provider: npm
  email: gilbarbara@gmail.com
  api_key:
    secure: udTSoiJXNkpRBrbwNtzflguIc/QvRbW/xdajwJqYUxitA409jBO+VhsxwlDJBl0HHHKW7yOwTUXvKAxr92y/6FByVM9yLuduQLOvG9J++l12Lc7fehKXbuNBZZDwjUF3MwftF9mCj4gJTUPrajZjXxUx78hI7dTCjJuJkpXHfZSr00Xu8In59rzr9OhDGBITlMSynE0yEIVBEfboxf9q5uSuJtp6qaK5ohbZqQnz2KIVoI2TUZ9KXpU8765mAd5xxvF4kgpmLYFN9TSd49oipZYPZs4UjlfVrPmKq2nmzepew9HuaXEvg0DLpcI9YjzBkR4AGlRIal2t4gNmy9m2XbaeyTS5q5Aoa+UchR9GS+LLsBIfl+1bI9yqijURZp68xMdQRC2iUrPcJeTKY9WpXEYFjxPmJXqfQl2BAiOlaxCzvNnD2i8th6PpeI+2aU79pWRSwUSQqV4PLjDN+M86cEpVRxZePLte6RIVqtRBes9HY8sQph0MAdzLUTbmMehnB1XzSRbuR77687NrbW8epRsxqRSK2Uqman8ZWSJan9apwP4niVciDJbfVL9M1J7pUZX8HKvfC3l5NJWO69xzQFouSVhtkZZWU4bxGtgS5gM+H/AHKv9/qktoA/K8hGPEFR1S7OoWSP310wetGHMHuXniKQh7glDh/IkpFp8QF14=
  on:
    tags: true
    repo: gilbarbara/react-joyride
addons:
    code_climate:
        repo_token: f5f9b3ad4d0ec4f05f0ed8b57a530044671d02bf264c3772ba67e0371442401f